Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "vodka")
Ingredient.create(name: "coca")
Ingredient.create(name: "rhum")
Ingredient.create(name: "whisky")